version: '3.8'

services:
  # Banco de dados MariaDB
  database:
    image: mariadb:10.9
    container_name: sistema_cadastro_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sistema_cadastro
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - sistema_network

  # Backend Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sistema_cadastro_backend
    restart: unless-stopped
    depends_on:
      - database
    environment:
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: sistema_cadastro
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_password
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: base64:YourAppKeyHere
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    ports:
      - "8000:8000"
    networks:
      - sistema_network
    command: >
      sh -c "
        sleep 30 &&
        php artisan migrate --force &&
        php artisan db:seed --force &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

  # Frontend Vue
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sistema_cadastro_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - sistema_network

volumes:
  db_data:

networks:
  sistema_network:
    driver: bridge

